OPTIONS (ERRORS=99999)
LOAD DATA 
INFILE * "str '\r'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "T_ACCOUNT_SUMMARY"
FIELDS TERMINATED BY'	'
TRAILING NULLCOLS 
( 
"DATE" BOUNDFILLER ,
"TRANTIME" "TO_DATE(:DATE||' '||:TRANTIME, 'DD MON YY HH24:MI')" ,
"TRANTYPE" CHAR (48) ,
"TRANDESC" CHAR (128) ,
"CREDIT" ,
"DEBET" ,
"BALANCE" ,
"CURRENCY" CHAR(3) 
)
