OPTIONS (ERRORS=999999)
LOAD DATA 
INFILE * "str '\r'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "T_CLOSED_POSITIONS"
FIELDS TERMINATED BY'	'
TRAILING NULLCOLS ( 
"PRODUCT" CHAR (80),
"BETACTION" CHAR (10),
"BET#" ,
"BETOPEN" ,
"BETCLOSE" ,
"PROFITBRUTTO" ,
"PROFIT" ,
"TIMEOPEN" DATE "DD/MM/YYYY HH24:MI:SS" ,
"TIMECLOSE" DATE "DD/MM/YYYY HH24:MI:SS" )
